display_name: flix
package_name: flix

maintainer:
  name: zhangjian
  email: 2242634757@qq.com
priority: optional
section: x11
installed_size: 24400
dependcies:
  - libnotify-bin
  - libappindicator3-1
essential: false
icon: linux/resources/flix.png
postuninstall_scripts:
  - echo "Sorry to see you go."
keywords:
  - flix
  - file show

generic_name: flix
categories:
  - Utility

startup_notify: true