display_name: flix
package_name: flix

maintainer:
  name: zhangjian
  email: 2242634757@qq.com
priority: optional
section: x11
installed_size: 24400
dependencies:
  - libnotify-bin
  - libappindicator3-1
  - libgtk-3-0
essential: false
icon: linux/resources/flix.png
keywords:
  - flix

generic_name: flix
categories:
  - Tool

startup_notify: true
