name: Build All

on:
  workflow_dispatch:
  push:
    tags:
        - 'v*'

jobs:
   android:
     uses: ./.github/workflows/android.yml

   ios:
     uses: ./.github/workflows/ios.yml

   linux:
     uses: ./.github/workflows/linux.yml

   windows:
     uses: ./.github/workflows/windows.yml

   darwin:
     uses: ./.github/workflows/darwin.yml