name: Build All
on:
  workflow_dispatch:
    inputs:
      up_load:
        description: 'Upload artifacts and to TestFlight'
        type: boolean
        required: true
        default: true
      skip_android:
        description: 'Skip Android build'
        type: boolean
        default: false
      skip_ios:
        description: 'Skip iOS build'
        type: boolean
        default: true
      skip_linux:
        description: 'Skip Linux build'
        type: boolean
        default: false
      skip_windows:
        description: 'Skip Windows build'
        type: boolean
        default: false
      skip_darwin:
        description: 'Skip macOS build'
        type: boolean
        default: true
  workflow_call:
    inputs:
      up_load:
        description: 'Upload artifacts and to TestFlight'
        type: boolean
        required: true
        default: true
      skip_android:
        description: 'Skip Android build'
        type: boolean
        default: false
      skip_ios:
        description: 'Skip iOS build'
        type: boolean
        default: false
      skip_linux:
        description: 'Skip Linux build'
        type: boolean
        default: false
      skip_windows:
        description: 'Skip Windows build'
        type: boolean
        default: false
      skip_darwin:
        description: 'Skip macOS build'
        type: boolean
        default: false

jobs:
   android:
    if: ${{ !inputs.skip_android }}
    uses: ./.github/workflows/android.yml
    with:
      up_load: ${{ inputs.up_load }}
      split_per_abi_apk: false
      single_apk: true
      app_bundle: false

   ios:
    if: ${{ !inputs.skip_ios }}
    uses: ./.github/workflows/ios.yml
    with:
      up_tf: ${{ inputs.up_load }}

   linux:
    if: ${{ !inputs.skip_linux }}
    uses: ./.github/workflows/linux.yml
    with:
      up_load: ${{ inputs.up_load }}

   windows:
    if: ${{ !inputs.skip_windows }}
    uses: ./.github/workflows/windows.yml
    with:
      up_load: ${{ inputs.up_load }}
      installer: true
      portable: true

   darwin:
    if: ${{ !inputs.skip_darwin }}
    uses: ./.github/workflows/darwin.yml
    with:
      up_load: ${{ inputs.up_load }}