name: Build apk and bundle
on:
  workflow_dispatch:
  workflow_call:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # You can use 'zulu' or 'adopt' based on your preference
          java-version: '17'
      - name: Verify Java version
        run: java -version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
      - run: flutter pub get
      - name: Build apks split per abi
        run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --release
      - name: Build single huge apk
        run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/
      - run: flutter build appbundle
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/
