name: Gen i10n

# on push to files in i10n folder,
# set up flutter
# run `flutter pub global run intl_utils:generate` to generate i10n files
# check if there are changes in the lib/i10n/ files
# and push the changes to the repo

on:
  push:
    paths:
      - 'i10n/**'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: 3.24.0
        - run: flutter pub get
        - run: flutter pub global run intl_utils:generate
        - name: Check for changes
          run: |
            git diff --exit-code || git commit -am "Auto Update i10n files"
        - name: Push changes
          run: |
            git push