name: Gen l10n

# on push to files in i10n folder,
# set up flutter
# generate i10n files
# check if there are changes in the lib/l10n/ files
# and push the changes to the repo

on:
  push:
    paths:
      - 'l10n/**'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: 3.24.0
        - run: flutter pub get
        - run: |
            dart run intl_translation:extract_to_arb --output-dir=lib/l10n lib/main.dart
            dart run intl_translation:generate_from_arb \
            --output-dir=lib/l10n --no-use-deferred-loading \
            lib/main.dart lib/l10n/intl_*.arb
        - name: Check for changes
          run: |
            git diff --exit-code || git commit -am "Auto Update l10n files"
        - name: Push changes
          run: |
            git push