name: Build MacOS
on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build macos
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/macos/Build/Products/Release/

