name: Build Release
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build to Artifacts
    uses: ./.github/workflows/all.yaml
    with:
      up_load: true
      skip_darwin: true
  upload:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download All Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Zip all subdirectories
        run: |
          for d in artifacts/*; do
            zip -r "${d}.zip" "$d"
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    name: Cleanup Artifacts
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            android-*
            linux-*
            windows-*
        
