name: Build Windows Installer
on:
  workflow_dispatch:
    inputs:
      up_load:
        description: 'Upload artifacts'
        type: boolean
        required: true
        default: true
      installer:
        description: 'Build Installer'
        type: boolean
        required: true
        default: true
      portable:
        description: 'Build Portable Package'
        type: boolean
        required: true
        default: true
  workflow_call:
    inputs:
      up_load:
        description: 'Upload artifacts'
        type: boolean
        required: true
        default: true
      installer:
        description: 'Build Installer'
        type: boolean
        required: true
        default: true
      portable:
        description: 'Build Portable Package'
        type: boolean
        required: true
        default: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run make windows
      - name: Upload Installer
        if: ${{ inputs.up_load && inputs.installer }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ./scripts/Installer/publish
      - name: Upload Portable Package
        if: ${{ inputs.up_load && inputs.portable }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: ./scripts/Installer/portable
      - name: Upload R2
        if: ${{ inputs.up_load }}
        uses: magicwallet/r2-upload@main
        with:
          endpoint: ${{ secrets.R2_ENDPOINT }}
          access_key_id: ${{ secrets.R2_KEY }}
          secret_access_key: ${{ secrets.R2_SECRET }}
          file: scripts/Installer/publish/*
          bucket: flix
          destination: /$(date +'%Y-%m-%d-%H')-${{ github.sha }}
      #zip ./scripts/Installer/portable/flix to win_portable.zip
      - name: Zip Portable Package
        if: ${{ inputs.up_load && inputs.portable }}
        run: Compress-Archive -Path ./scripts/Installer/portable/flix -DestinationPath ./win_portable.zip
      - name: Upload R2
        if: ${{ inputs.up_load }}
        uses: magicwallet/r2-upload@main
        with:
          endpoint: ${{ secrets.R2_ENDPOINT }}
          access_key_id: ${{ secrets.R2_KEY }}
          secret_access_key: ${{ secrets.R2_SECRET }}
          file: ./win_portable.zip
          bucket: flix
          destination: /$(date +'%Y-%m-%d-%H')-${{ github.sha }}