name: Build Windows Installer
on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
      - run: dart run make windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./scripts/Installer/publish
